export const SwiftCodes = [ 
  {
    label: 'ADDCJPJT',
    value: 'ADDCJPJT',
  },
  {
    label: 'AEONJPJT',
    value: 'AEONJPJT',
  },
  {
    label: 'ALSJJPJT',
    value: 'ALSJJPJT',
  },
  {
    label: 'GGCAJPJT',
    value: 'GGCAJPJT',
  },
  {
    label: 'ABOCJPJT',
    value: 'ABOCJPJT',
  },
  {
    label: 'AICHJPJN',
    value: 'AICHJPJN',
  },
  {
    label: 'AKITJPJT',
    value: 'AKITJPJT',
  },
  {
    label: 'AMASJPJZ',
    value: 'AMASJPJZ',
  },
  {
    label: 'AOMBJPJT',
    value: 'AOMBJPJT',
  },
  {
    label: 'NCBTJPJT',
    value: 'NCBTJPJT',
  },
  {
    label: 'ASGHJPJT',
    value: 'ASGHJPJT',
  },
  {
    label: 'AKACJPJT',
    value: 'AKACJPJT',
  },
  {
    label: 'ASKBJPJT',
    value: 'ASKBJPJT',
  },
  {
    label: 'ASIKJPJT',
    value: 'ASIKJPJT',
  },
  {
    label: 'JICRJPJT',
    value: 'JICRJPJT',
  },
  {
    label: 'ANZBJPJX',
    value: 'ANZBJPJX',
  },
  {
    label: 'AWABJPJT',
    value: 'AWABJPJT',
  },
  {
    label: 'AXIPJPJT',
    value: 'AXIPJPJT',
  },
  {
    label: 'AXIPJPJTCRI',
    value: 'AXIPJPJTCRI',
  },
  {
    label: 'AXIPJPJTIDN',
    value: 'AXIPJPJTIDN',
  },
  {
    label: 'AXIPJPJTPHI',
    value: 'AXIPJPJTPHI',
  },
  {
    label: 'AXIPJPJTSGP',
    value: 'AXIPJPJTSGP',
  },
  {
    label: 'AZBCJPJT',
    value: 'AZBCJPJT',
  },
  {
    label: 'BBVAJPJT',
    value: 'BBVAJPJT',
  },
  {
    label: 'BRASJPJT',
    value: 'BRASJPJT',
  },
  {
    label: 'BNDCJPJT',
    value: 'BNDCJPJT',
  },
  {
    label: 'BKKBJPJT',
    value: 'BKKBJPJT',
  },
  {
    label: 'BKKBJPJTOSA',
    value: 'BKKBJPJTOSA',
  },
  {
    label: 'BNINJPJT',
    value: 'BNINJPJT',
  },
  {
    label: 'BOFAJPJXCMS',
    value: 'BOFAJPJXCMS',
  },
  {
    label: 'BOFAJPJXJGB',
    value: 'BOFAJPJXJGB',
  },
  {
    label: 'BOFAJPJX',
    value: 'BOFAJPJX',
  },
  {
    label: 'BKCHJPJTCNY',
    value: 'BKCHJPJTCNY',
  },
  {
    label: 'BKCHJPJT',
    value: 'BKCHJPJT',
  },
  {
    label: 'BKCHJPJTNGY',
    value: 'BKCHJPJTNGY',
  },
  {
    label: 'BKCHJPJTOSA',
    value: 'BKCHJPJTOSA',
  },
  {
    label: 'BKCHJPJTOTM',
    value: 'BKCHJPJTOTM',
  },
  {
    label: 'BKCHJPJTYHA',
    value: 'BKCHJPJTYHA',
  },
  {
    label: 'COMMJPJT',
    value: 'COMMJPJT',
  },
  {
    label: 'FKBKJPJT',
    value: 'FKBKJPJT',
  },
  {
    label: 'FKBKJPJT100',
    value: 'FKBKJPJT100',
  },
  {
    label: 'BKIDJPJT',
    value: 'BKIDJPJT',
  },
  {
    label: 'BKIDJPJTOSK',
    value: 'BKIDJPJTOSK',
  },
  {
    label: 'BAIWJPJT',
    value: 'BAIWJPJT',
  },
  {
    label: 'BOJPJPJT',
    value: 'BOJPJPJT',
  },
  {
    label: 'BOJPJPJTBJ1',
    value: 'BOJPJPJTBJ1',
  },
  {
    label: 'BOJPJPJTMF1',
    value: 'BOJPJPJTMF1',
  },
  {
    label: 'BOKFJPJZ',
    value: 'BOKFJPJZ',
  },
  {
    label: 'NAGOJPJN',
    value: 'NAGOJPJN',
  },
  {
    label: 'BOKIJPJZ',
    value: 'BOKIJPJZ',
  },
  {
    label: 'BKSGJPJT',
    value: 'BKSGJPJT',
  },
  {
    label: 'BKSGJPJTSAG',
    value: 'BKSGJPJTSAG',
  },
  {
    label: 'BKTWJPJT',
    value: 'BKTWJPJT',
  },
  {
    label: 'RYUBJPJZ',
    value: 'RYUBJPJZ',
  },
  {
    label: 'HAMAJPJT',
    value: 'HAMAJPJT',
  },
  {
    label: 'BARCJPJ2',
    value: 'BARCJPJ2',
  },
  {
    label: 'BARCJPJ2MFX',
    value: 'BARCJPJ2MFX',
  },
  {
    label: 'BARCJPJ9',
    value: 'BARCJPJ9',
  },
  {
    label: 'CFILJPJT',
    value: 'CFILJPJT',
  },
  {
    label: 'BITFJPJ2',
    value: 'BITFJPJ2',
  },
  {
    label: 'BNPAJPJT',
    value: 'BNPAJPJT',
  },
  {
    label: 'BNPAJPJ2',
    value: 'BNPAJPJ2',
  },
  {
    label: 'MELNJPJT',
    value: 'MELNJPJT',
  },
  {
    label: 'MLCOJPJD',
    value: 'MLCOJPJD',
  },
  {
    label: 'MLCOJPJT',
    value: 'MLCOJPJT',
  },
  {
    label: 'MLCOJPJX',
    value: 'MLCOJPJX',
  },
  {
    label: 'MLCOJPJTJGB',
    value: 'MLCOJPJTJGB',
  },
  {
    label: 'MLCOJPJTJES',
    value: 'MLCOJPJTJES',
  },
  {
    label: 'MLCOJPJTSDI',
    value: 'MLCOJPJTSDI',
  },
  {
    label: 'MLCOJPJTTSY',
    value: 'MLCOJPJTTSY',
  },
  {
    label: 'BBHCJPJT',
    value: 'BBHCJPJT',
  },
  {
    label: 'CTRLJPJT',
    value: 'CTRLJPJT',
  },
  {
    label: 'CCBCJPJT',
    value: 'CCBCJPJT',
  },
  {
    label: 'CHBAJPJT',
    value: 'CHBAJPJT',
  },
  {
    label: 'CHIKJPJT',
    value: 'CHIKJPJT',
  },
  {
    label: 'PCBCJPJT',
    value: 'PCBCJPJT',
  },
  {
    label: 'CHGKJPJT',
    value: 'CHGKJPJT',
  },
  {
    label: 'CHGKJPJZ',
    value: 'CHGKJPJZ',
  },
  {
    label: 'CKBKJPJN',
    value: 'CKBKJPJN',
  },
  {
    label: 'CIWMJPJT',
    value: 'CIWMJPJT',
  },
  {
    label: 'CITIJPJT',
    value: 'CITIJPJT',
  },
  {
    label: 'NSBLJPJT',
    value: 'NSBLJPJT',
  },
  {
    label: 'COBAJPJX',
    value: 'COBAJPJX',
  },
  {
    label: 'COBAJPJXTOM',
    value: 'COBAJPJXTOM',
  },
  {
    label: 'CTBAJPJT',
    value: 'CTBAJPJT',
  },
  {
    label: 'BSUIJPJT',
    value: 'BSUIJPJT',
  },
  {
    label: 'BSUIJPJTCOM',
    value: 'BSUIJPJTCOM',
  },
  {
    label: 'CRLYJPJ9',
    value: 'CRLYJPJ9',
  },
  {
    label: 'CRESJPJT',
    value: 'CRESJPJT',
  },
  {
    label: 'CRESJPJTPBS',
    value: 'CRESJPJTPBS',
  },
  {
    label: 'CSFBJPJX',
    value: 'CSFBJPJX',
  },
  {
    label: 'CSFBJPJXVIS',
    value: 'CSFBJPJXVIS',
  },
  {
    label: 'CSFBJPJXEQT',
    value: 'CSFBJPJXEQT',
  },
  {
    label: 'CSFBJPJXPBS',
    value: 'CSFBJPJXPBS',
  },
  {
    label: 'CTCBJPJT',
    value: 'CTCBJPJT',
  },
  {
    label: 'TCSBJPJT',
    value: 'TCSBJPJT',
  },
  {
    label: 'TCSBJPJ2',
    value: 'TCSBJPJ2',
  },
  {
    label: 'JTSBJPJT',
    value: 'JTSBJPJT',
  },
  {
    label: 'JTSBJPJTAGE',
    value: 'JTSBJPJTAGE',
  },
  {
    label: 'DAISJPJT',
    value: 'DAISJPJT',
  },
  {
    label: 'DAMLJPJA',
    value: 'DAMLJPJA',
  },
  {
    label: 'DNEXJPJT',
    value: 'DNEXJPJT',
  },
  {
    label: 'DWSCJPJT',
    value: 'DWSCJPJT',
  },
  {
    label: 'DWSCJPJTJSS',
    value: 'DWSCJPJTJSS',
  },
  {
    label: 'DWSCJPJTCLS',
    value: 'DWSCJPJTCLS',
  },
  {
    label: 'DBSSJPJT',
    value: 'DBSSJPJT',
  },
  {
    label: 'DEUTJPJTFX1',
    value: 'DEUTJPJTFX1',
  },
  {
    label: 'DEUTJPJT',
    value: 'DEUTJPJT',
  },
  {
    label: 'DEUTJPJ7',
    value: 'DEUTJPJ7',
  },
  {
    label: 'DEUTJPJ9',
    value: 'DEUTJPJ9',
  },
  {
    label: 'DEUTJPJ9FIC',
    value: 'DEUTJPJ9FIC',
  },
  {
    label: 'DEUTJPJ9EQD',
    value: 'DEUTJPJ9EQD',
  },
  {
    label: 'DEUTJPJ9EQT',
    value: 'DEUTJPJ9EQT',
  },
  {
    label: 'DEUTJPJ9FX1',
    value: 'DEUTJPJ9FX1',
  },
  {
    label: 'DEUTJPJ9DOM',
    value: 'DEUTJPJ9DOM',
  },
  {
    label: 'DICJJPJT',
    value: 'DICJJPJT',
  },
  {
    label: 'DEAMJPJT',
    value: 'DEAMJPJT',
  },
  {
    label: 'ESUNJPJT',
    value: 'ESUNJPJT',
  },
  {
    label: 'EBCPJPJT',
    value: 'EBCPJPJT',
  },
  {
    label: 'EISAJPJT',
    value: 'EISAJPJT',
  },
  {
    label: 'FRUQJPJT',
    value: 'FRUQJPJT',
  },
  {
    label: 'FRUQJPJ2',
    value: 'FRUQJPJ2',
  },
  {
    label: 'FCBKJPJT',
    value: 'FCBKJPJT',
  },
  {
    label: 'FKUIJPJT',
    value: 'FKUIJPJT',
  },
  {
    label: 'AIGJJPJT',
    value: 'AIGJJPJT',
  },
  {
    label: 'GAAIJPJ2',
    value: 'GAAIJPJ2',
  },
  {
    label: 'GFSBJPJZ',
    value: 'GFSBJPJZ',
  },
  {
    label: 'GLJAJPJ2',
    value: 'GLJAJPJ2',
  },
  {
    label: 'GSAMJPJT',
    value: 'GSAMJPJT',
  },
  {
    label: 'GSCRJPJT',
    value: 'GSCRJPJT',
  },
  {
    label: 'GOLDJPJXMRA',
    value: 'GOLDJPJXMRA',
  },
  {
    label: 'GOLDJPJX',
    value: 'GOLDJPJX',
  },
  {
    label: 'GUMAJPJT',
    value: 'GUMAJPJT',
  },
  {
    label: 'HABKJPJT',
    value: 'HABKJPJT',
  },
  {
    label: 'HAELJPJN',
    value: 'HAELJPJN',
  },
  {
    label: 'HIROJPJT',
    value: 'HIROJPJT',
  },
  {
    label: 'HICCJP22',
    value: 'HICCJP22',
  },
  {
    label: 'HIHCJPJT',
    value: 'HIHCJPJT',
  },
  {
    label: 'HKDBJPJT',
    value: 'HKDBJPJT',
  },
  {
    label: 'HKOKJPJT',
    value: 'HKOKJPJT',
  },
  {
    label: 'HOKBJPJT',
    value: 'HOKBJPJT',
  },
  {
    label: 'HSBCJPJT',
    value: 'HSBCJPJT',
  },
  {
    label: 'HSBCJPJTCLS',
    value: 'HSBCJPJTCLS',
  },
  {
    label: 'HSBCJPJTTRS',
    value: 'HSBCJPJTTRS',
  },
  {
    label: 'IBJPJPJT',
    value: 'IBJPJPJT',
  },
  {
    label: 'HUJPJPJ2',
    value: 'HUJPJPJ2',
  },
  {
    label: 'HYKGJPJT',
    value: 'HYKGJPJT',
  },
  {
    label: 'HYKGJPJTTSU',
    value: 'HYKGJPJTTSU',
  },
  {
    label: 'HYAKJPJT',
    value: 'HYAKJPJT',
  },
  {
    label: 'ICBKJPJT',
    value: 'ICBKJPJT',
  },
  {
    label: 'IBKOJPJT',
    value: 'IBKOJPJT',
  },
  {
    label: 'INGBJPJT',
    value: 'INGBJPJT',
  },
  {
    label: 'BCITJPJT',
    value: 'BCITJPJT',
  },
  {
    label: 'COSSJPJT',
    value: 'COSSJPJT',
  },
  {
    label: 'IYOBJPJT',
    value: 'IYOBJPJT',
  },
  {
    label: 'JPPSJPJK',
    value: 'JPPSJPJK',
  },
  {
    label: 'JPPSJPJJ',
    value: 'JPPSJPJJ',
  },
  {
    label: 'JPPSJPJJIRS',
    value: 'JPPSJPJJIRS',
  },
  {
    label: 'JJSDJPJT',
    value: 'JJSDJPJT',
  },
  {
    label: 'JSBKJPJT',
    value: 'JSBKJPJT',
  },
  {
    label: 'OJISJPJT',
    value: 'OJISJPJT',
  },
  {
    label: 'JOYOJPJT',
    value: 'JOYOJPJT',
  },
  {
    label: 'CHASJPJZ',
    value: 'CHASJPJZ',
  },
  {
    label: 'CHASJPJTTRO',
    value: 'CHASJPJTTRO',
  },
  {
    label: 'CHASJPJT',
    value: 'CHASJPJT',
  },
  {
    label: 'CHASJPJTWSS',
    value: 'CHASJPJTWSS',
  },
  {
    label: 'CHASJPJTENQ',
    value: 'CHASJPJTENQ',
  },
  {
    label: 'CHASJPJTTSD',
    value: 'CHASJPJTTSD',
  },
  {
    label: 'CHASJPJ9',
    value: 'CHASJPJ9',
  },
  {
    label: 'CHASJPJ9CE1',
    value: 'CHASJPJ9CE1',
  },
  {
    label: 'CHASJPJ9EQT',
    value: 'CHASJPJ9EQT',
  },
  {
    label: 'SHWAJPJT',
    value: 'SHWAJPJT',
  },
  {
    label: 'JUROJPJT',
    value: 'JUROJPJT',
  },
  {
    label: 'KGWBJPJZ',
    value: 'KGWBJPJZ',
  },
  {
    label: 'KAGOJPJT',
    value: 'KAGOJPJT',
  },
  {
    label: 'OSABJPJS',
    value: 'OSABJPJS',
  },
  {
    label: 'KAOCJPJT',
    value: 'KAOCJPJT',
  },
  {
    label: 'KDDIJPJT',
    value: 'KDDIJPJT',
  },
  {
    label: 'KOEXJPJT',
    value: 'KOEXJPJT',
  },
  {
    label: 'KOEXJPJTFUK',
    value: 'KOEXJPJTFUK',
  },
  {
    label: 'KOEXJPJTOSA',
    value: 'KOEXJPJTOSA',
  },
  {
    label: 'KEIBJPJT',
    value: 'KEIBJPJT',
  },
  {
    label: 'TOMIJPJT',
    value: 'TOMIJPJT',
  },
  {
    label: 'KIHCJPJJ',
    value: 'KIHCJPJJ',
  },
  {
    label: 'KNPBJPJT',
    value: 'KNPBJPJT',
  },
  {
    label: 'KITQJPJZ',
    value: 'KITQJPJZ',
  },
  {
    label: 'KIYOJPJT',
    value: 'KIYOJPJT',
  },
  {
    label: 'KOTTJPJJ',
    value: 'KOTTJPJJ',
  },
  {
    label: 'CZNBJPJT',
    value: 'CZNBJPJT',
  },
  {
    label: 'KODBJPJT',
    value: 'KODBJPJT',
  },
  {
    label: 'KUMAJPJZ',
    value: 'KUMAJPJZ',
  },
  {
    label: 'KCHUJPJY',
    value: 'KCHUJPJY',
  },
  {
    label: 'KYSBJPJZ',
    value: 'KYSBJPJZ',
  },
  {
    label: 'LOCYJPJT',
    value: 'LOCYJPJT',
  },
  {
    label: 'LOCYJPJTNDP',
    value: 'LOCYJPJTNDP',
  },
  {
    label: 'MFEHJPJM',
    value: 'MFEHJPJM',
  },
  {
    label: 'MFCTJPJT',
    value: 'MFCTJPJT',
  },
  {
    label: 'MRPTJPJ2',
    value: 'MRPTJPJ2',
  },
  {
    label: 'ICBCJPJT',
    value: 'ICBCJPJT',
  },
  {
    label: 'ICBCJPJTOSA',
    value: 'ICBCJPJTOSA',
  },
  {
    label: 'MYLIJPJT',
    value: 'MYLIJPJT',
  },
  {
    label: 'DAIXJPJT',
    value: 'DAIXJPJT',
  },
  {
    label: 'MBTCJPJT',
    value: 'MBTCJPJT',
  },
  {
    label: 'HSINJPJK',
    value: 'HSINJPJK',
  },
  {
    label: 'MIGPJPJT',
    value: 'MIGPJPJT',
  },
  {
    label: 'MISCJPJ2',
    value: 'MISCJPJ2',
  },
  {
    label: 'MCOPJPJJ',
    value: 'MCOPJPJJ',
  },
  {
    label: 'DTAPJPJKCNY',
    value: 'DTAPJPJKCNY',
  },
  {
    label: 'DTAPJPJK',
    value: 'DTAPJPJK',
  },
  {
    label: 'MUMLJPJT',
    value: 'MUMLJPJT',
  },
  {
    label: 'KKSSJPJT',
    value: 'KKSSJPJT',
  },
  {
    label: 'MUSHJP22',
    value: 'MUSHJP22',
  },
  {
    label: 'MTBCJPJT',
    value: 'MTBCJPJT',
  },
  {
    label: 'MIYAJPJT',
    value: 'MIYAJPJT',
  },
  {
    label: 'MHCBJPJT',
    value: 'MHCBJPJT',
  },
  {
    label: 'MHCBJPJTCLS',
    value: 'MHCBJPJTCLS',
  },
  {
    label: 'MHCBJPJ4',
    value: 'MHCBJPJ4',
  },
  {
    label: 'MHCBJPJ5',
    value: 'MHCBJPJ5',
  },
  {
    label: 'MHCBJPJ6',
    value: 'MHCBJPJ6',
  },
  {
    label: 'MHCBJPJ2',
    value: 'MHCBJPJ2',
  },
  {
    label: 'MHSCJPJT',
    value: 'MHSCJPJT',
  },
  {
    label: 'MHSCJPJ2',
    value: 'MHSCJPJ2',
  },
  {
    label: 'YTBCJPJT',
    value: 'YTBCJPJT',
  },
  {
    label: 'HRSBJPJT',
    value: 'HRSBJPJT',
  },
  {
    label: 'MSTKJPJX',
    value: 'MSTKJPJX',
  },
  {
    label: 'MSTKJPJXCII',
    value: 'MSTKJPJXCII',
  },
  {
    label: 'MSTKJPJXCLS',
    value: 'MSTKJPJXCLS',
  },
  {
    label: 'MSTKJPJXFXO',
    value: 'MSTKJPJXFXO',
  },
  {
    label: 'BOTKJPJT',
    value: 'BOTKJPJT',
  },
  {
    label: 'BOTKJPJTCLS',
    value: 'BOTKJPJTCLS',
  },
  {
    label: 'BOTKJPJTFUK',
    value: 'BOTKJPJTFUK',
  },
  {
    label: 'BOTKJPJTHIR',
    value: 'BOTKJPJTHIR',
  },
  {
    label: 'BOTKJPJTSMO',
    value: 'BOTKJPJTSMO',
  },
  {
    label: 'BOTKJPJTKOB',
    value: 'BOTKJPJTKOB',
  },
  {
    label: 'BOTKJPJTNGY',
    value: 'BOTKJPJTNGY',
  },
  {
    label: 'BOTKJPJTOSA',
    value: 'BOTKJPJTOSA',
  },
  {
    label: 'BOTKJPJTSAP',
    value: 'BOTKJPJTSAP',
  },
  {
    label: 'BOTKJPJTFGN',
    value: 'BOTKJPJTFGN',
  },
  {
    label: 'BOTKJPJ2',
    value: 'BOTKJPJ2',
  },
  {
    label: 'BOTKJPJTFND',
    value: 'BOTKJPJTFND',
  },
  {
    label: 'BOTKJPJTSAD',
    value: 'BOTKJPJTSAD',
  },
  {
    label: 'MUBKJPJT',
    value: 'MUBKJPJT',
  },
  {
    label: 'MUBKJPJTTSD',
    value: 'MUBKJPJTTSD',
  },
  {
    label: 'NDXEJPJT',
    value: 'NDXEJPJT',
  },
  {
    label: 'NAGAJPJZ',
    value: 'NAGAJPJZ',
  },
  {
    label: 'NANTJPJT',
    value: 'NANTJPJT',
  },
  {
    label: 'NATAJPJT',
    value: 'NATAJPJT',
  },
  {
    label: 'NBPAJPJT',
    value: 'NBPAJPJT',
  },
  {
    label: 'NBPAJPJTOSK',
    value: 'NBPAJPJTOSK',
  },
  {
    label: 'ZENKJPJJ',
    value: 'ZENKJPJJ',
  },
  {
    label: 'NATXJPJT',
    value: 'NATXJPJT',
  },
  {
    label: 'NWSJJPJT',
    value: 'NWSJJPJT',
  },
  {
    label: 'NCORJPJT',
    value: 'NCORJPJT',
  },
  {
    label: 'NIFCJPJT',
    value: 'NIFCJPJT',
  },
  {
    label: 'NLICJP22',
    value: 'NLICJP22',
  },
  {
    label: 'NYKKJPJJ',
    value: 'NYKKJPJJ',
  },
  {
    label: 'NAMJJPJT',
    value: 'NAMJJPJT',
  },
  {
    label: 'NSSNJPJT',
    value: 'NSSNJPJT',
  },
  {
    label: 'NIHOJPJT',
    value: 'NIHOJPJT',
  },
  {
    label: 'NAMKJPJT',
    value: 'NAMKJPJT',
  },
  {
    label: 'NAMKJPJTFDV',
    value: 'NAMKJPJTFDV',
  },
  {
    label: 'NAMKJPJTADV',
    value: 'NAMKJPJTADV',
  },
  {
    label: 'NAMKJPJTBFT',
    value: 'NAMKJPJTBFT',
  },
  {
    label: 'NFPSJPJT',
    value: 'NFPSJPJT',
  },
  {
    label: 'NFPSJPJTCCS',
    value: 'NFPSJPJTCCS',
  },
  {
    label: 'NMRAJPJT',
    value: 'NMRAJPJT',
  },
  {
    label: 'NMRSJPJT',
    value: 'NMRSJPJT',
  },
  {
    label: 'NOCUJPJT',
    value: 'NOCUJPJT',
  },
  {
    label: 'NOCUJPJTCLS',
    value: 'NOCUJPJTCLS',
  },
  {
    label: 'NORPJPJP',
    value: 'NORPJPJP',
  },
  {
    label: 'OGAKJPJT',
    value: 'OGAKJPJT',
  },
  {
    label: 'OITAJPJT',
    value: 'OITAJPJT',
  },
  {
    label: 'OKASJPJT',
    value: 'OKASJPJT',
  },
  {
    label: 'OKSBJPJZ',
    value: 'OKSBJPJZ',
  },
  {
    label: 'OMRNJPJT',
    value: 'OMRNJPJT',
  },
  {
    label: 'OSACJPJS',
    value: 'OSACJPJS',
  },
  {
    label: 'OCBCJPJT',
    value: 'OCBCJPJT',
  },
  {
    label: 'PANAJPJP',
    value: 'PANAJPJP',
  },
  {
    label: 'PANAJPJS',
    value: 'PANAJPJS',
  },
  {
    label: 'JANEJPJT',
    value: 'JANEJPJT',
  },
  {
    label: 'PNBMJPJT',
    value: 'PNBMJPJT',
  },
  {
    label: 'PICTJPJT',
    value: 'PICTJPJT',
  },
  {
    label: 'PGHQJPJT',
    value: 'PGHQJPJT',
  },
  {
    label: 'QBCPJPJT',
    value: 'QBCPJPJT',
  },
  {
    label: 'RAKTJPJT',
    value: 'RAKTJPJT',
  },
  {
    label: 'RBDSJPJT',
    value: 'RBDSJPJT',
  },
  {
    label: 'RCRTJPJJ',
    value: 'RCRTJPJJ',
  },
  {
    label: 'RESGJP22',
    value: 'RESGJP22',
  },
  {
    label: 'DIWAJPJT',
    value: 'DIWAJPJT',
  },
  {
    label: 'DIWAJPJA',
    value: 'DIWAJPJA',
  },
  {
    label: 'VTECJPJT',
    value: 'VTECJPJT',
  },
  {
    label: 'REVOJPJ2',
    value: 'REVOJPJ2',
  },
  {
    label: 'RICOJPJT',
    value: 'RICOJPJT',
  },
  {
    label: 'RODGJPJT',
    value: 'RODGJPJT',
  },
  {
    label: 'ROYCJPJT',
    value: 'ROYCJPJT',
  },
  {
    label: 'SIYOJPJJ',
    value: 'SIYOJPJJ',
  },
  {
    label: 'SAIBJPJT',
    value: 'SAIBJPJT',
  },
  {
    label: 'MIEBJPJT',
    value: 'MIEBJPJT',
  },
  {
    label: 'SGBKJPJTMAT',
    value: 'SGBKJPJTMAT',
  },
  {
    label: 'SGBKJPJT',
    value: 'SGBKJPJT',
  },
  {
    label: 'SLMCJPJJ',
    value: 'SLMCJPJJ',
  },
  {
    label: 'SBIRJPJT',
    value: 'SBIRJPJT',
  },
  {
    label: 'NTSSJPJT',
    value: 'NTSSJPJT',
  },
  {
    label: 'SSBKJPJZ',
    value: 'SSBKJPJZ',
  },
  {
    label: 'SVVNJPJJ',
    value: 'SVVNJPJJ',
  },
  {
    label: 'SIGAJPJT',
    value: 'SIGAJPJT',
  },
  {
    label: 'SIKOJPJT',
    value: 'SIKOJPJT',
  },
  {
    label: 'SMZGJPJT',
    value: 'SMZGJPJT',
  },
  {
    label: 'SHBKJPJX',
    value: 'SHBKJPJX',
  },
  {
    label: 'ZENBJPJT',
    value: 'ZENBJPJT',
  },
  {
    label: 'ZENBJPJ2',
    value: 'ZENBJPJ2',
  },
  {
    label: 'LTCBJPJT',
    value: 'LTCBJPJT',
  },
  {
    label: 'LTCBJPJTHED',
    value: 'LTCBJPJTHED',
  },
  {
    label: 'SHIZJPJT',
    value: 'SHIZJPJT',
  },
  {
    label: 'SKCKJPJT',
    value: 'SKCKJPJT',
  },
  {
    label: 'SNAIJPJT',
    value: 'SNAIJPJT',
  },
  {
    label: 'NKSCJPJT',
    value: 'NKSCJPJT',
  },
  {
    label: 'SMTCJPJ2',
    value: 'SMTCJPJ2',
  },
  {
    label: 'SMTCJPJT',
    value: 'SMTCJPJT',
  },
  {
    label: 'SMTCJPJ2BNK',
    value: 'SMTCJPJ2BNK',
  },
  {
    label: 'SOGEJPJT',
    value: 'SOGEJPJT',
  },
  {
    label: 'SGNPJPJT',
    value: 'SGNPJPJT',
  },
  {
    label: 'SNYBJPJT',
    value: 'SNYBJPJT',
  },
  {
    label: 'SPAXJPJT',
    value: 'SPAXJPJT',
  },
  {
    label: 'SCBLJPJT',
    value: 'SCBLJPJT',
  },
  {
    label: 'SBINJPJT',
    value: 'SBINJPJT',
  },
  {
    label: 'SBINJPJTOSA',
    value: 'SBINJPJTOSA',
  },
  {
    label: 'SBOSJPJX',
    value: 'SBOSJPJX',
  },
  {
    label: 'SSTBJPJX',
    value: 'SSTBJPJX',
  },
  {
    label: 'SSTBJPJXINS',
    value: 'SSTBJPJXINS',
  },
  {
    label: 'SSTBJPJXIAR',
    value: 'SSTBJPJXIAR',
  },
  {
    label: 'SSTBJPJXIMS',
    value: 'SSTBJPJXIMS',
  },
  {
    label: 'SSTBJPJXITM',
    value: 'SSTBJPJXITM',
  },
  {
    label: 'SSTBJPJXMTP',
    value: 'SSTBJPJXMTP',
  },
  {
    label: 'SSHBJPJT',
    value: 'SSHBJPJT',
  },
  {
    label: 'SUCPJPJT',
    value: 'SUCPJPJT',
  },
  {
    label: 'SMBCJPJT',
    value: 'SMBCJPJT',
  },
  {
    label: 'SMBCJPJTOSA',
    value: 'SMBCJPJTOSA',
  },
  {
    label: 'SMBCJPJTCLS',
    value: 'SMBCJPJTCLS',
  },
  {
    label: 'STBCJPJT',
    value: 'STBCJPJT',
  },
  {
    label: 'STBCJPJ2',
    value: 'STBCJPJ2',
  },
  {
    label: 'STBCJPJTCUS',
    value: 'STBCJPJTCUS',
  },
  {
    label: 'STBCJPJTCLS',
    value: 'STBCJPJTCLS',
  },
  {
    label: 'STBCJPJTSBS',
    value: 'STBCJPJTSBS',
  },
  {
    label: 'STBCJPJTSAD',
    value: 'STBCJPJTSAD',
  },
  {
    label: 'SBFDJPJT',
    value: 'SBFDJPJT',
  },
  {
    label: 'SRFXJPJT',
    value: 'SRFXJPJT',
  },
  {
    label: 'SWHQJPJT',
    value: 'SWHQJPJT',
  },
  {
    label: 'TJLIJPJT',
    value: 'TJLIJPJT',
  },
  {
    label: 'TSIBJPJT',
    value: 'TSIBJPJT',
  },
  {
    label: 'MBBTJPJT',
    value: 'MBBTJPJT',
  },
  {
    label: 'TJMAJPJZ',
    value: 'TJMAJPJZ',
  },
  {
    label: 'TAMAJPJT',
    value: 'TAMAJPJT',
  },
  {
    label: 'BOSSJPJT',
    value: 'BOSSJPJT',
  },
  {
    label: 'KOTIJPJZ',
    value: 'KOTIJPJZ',
  },
  {
    label: 'IRVTJPJT',
    value: 'IRVTJPJT',
  },
  {
    label: 'IRVTJPJX',
    value: 'IRVTJPJX',
  },
  {
    label: 'CHIHJPJT',
    value: 'CHIHJPJT',
  },
  {
    label: 'DFLIJPJ2',
    value: 'DFLIJPJ2',
  },
  {
    label: 'DLICJPJJ',
    value: 'DLICJPJJ',
  },
  {
    label: 'HIMEJPJT',
    value: 'HIMEJPJT',
  },
  {
    label: 'HNPBJPJT',
    value: 'HNPBJPJT',
  },
  {
    label: 'HIGOJPJT',
    value: 'HIGOJPJT',
  },
  {
    label: 'RIKBJPJT',
    value: 'RIKBJPJT',
  },
  {
    label: 'MTBJJPJT',
    value: 'MTBJJPJT',
  },
  {
    label: 'MTBJJPJTAGT',
    value: 'MTBJJPJTAGT',
  },
  {
    label: 'NISIJPJT',
    value: 'NISIJPJT',
  },
  {
    label: 'NISIJPJTFKK',
    value: 'NISIJPJTFKK',
  },
  {
    label: 'NMTBJPJT',
    value: 'NMTBJPJT',
  },
  {
    label: 'NMTBJPJTTAD',
    value: 'NMTBJPJTTAD',
  },
  {
    label: 'NMTBJPJTFXO',
    value: 'NMTBJPJTFXO',
  },
  {
    label: 'NMTBJPJTTRU',
    value: 'NMTBJPJTTRU',
  },
  {
    label: 'BIKEJPJS',
    value: 'BIKEJPJS',
  },
  {
    label: 'TOCIJPJT',
    value: 'TOCIJPJT',
  },
  {
    label: 'TKTSJPJT',
    value: 'TKTSJPJT',
  },
  {
    label: 'YOKRJPJT',
    value: 'YOKRJPJT',
  },
  {
    label: 'THKTJPJT',
    value: 'THKTJPJT',
  },
  {
    label: 'TSSTJPJT',
    value: 'TSSTJPJT',
  },
  {
    label: 'TOEIJPJT',
    value: 'TOEIJPJT',
  },
  {
    label: 'TOHOJPJT',
    value: 'TOHOJPJT',
  },
  {
    label: 'TTSEJPJT',
    value: 'TTSEJPJT',
  },
  {
    label: 'TMAJJPJT',
    value: 'TMAJJPJT',
  },
  {
    label: 'TKSBJPJZ',
    value: 'TKSBJPJZ',
  },
  {
    label: 'CHSBJPJT',
    value: 'CHSBJPJT',
  },
  {
    label: 'TSBKJPJT',
    value: 'TSBKJPJT',
  },
  {
    label: 'TOMAJPJZ',
    value: 'TOMAJPJZ',
  },
  {
    label: 'BIRDJPJZ',
    value: 'BIRDJPJZ',
  },
  {
    label: 'TOWAJPJT',
    value: 'TOWAJPJT',
  },
  {
    label: 'TOMCJP22',
    value: 'TOMCJP22',
  },
  {
    label: 'KGBKJPJT',
    value: 'KGBKJPJT',
  },
  {
    label: 'UBAFJPJX',
    value: 'UBAFJPJX',
  },
  {
    label: 'UACRJPJJ',
    value: 'UACRJPJJ',
  },
  {
    label: 'UBSWJPJT',
    value: 'UBSWJPJT',
  },
  {
    label: 'UBSWJPJTCLS',
    value: 'UBSWJPJTCLS',
  },
  {
    label: 'UBSAJPJT',
    value: 'UBSAJPJT',
  },
  {
    label: 'UBSWJPJ9',
    value: 'UBSWJPJ9',
  },
  {
    label: 'UBSTJPJ3',
    value: 'UBSTJPJ3',
  },
  {
    label: 'UYTCJPJT',
    value: 'UYTCJPJT',
  },
  {
    label: 'BVBEJPJT',
    value: 'BVBEJPJT',
  },
  {
    label: 'UOVBJPJT',
    value: 'UOVBJPJT',
  },
  {
    label: 'PNBPJPJX',
    value: 'PNBPJPJX',
  },
  {
    label: 'HVBKJPJT',
    value: 'HVBKJPJT',
  },
  {
    label: 'YAMBJPJT',
    value: 'YAMBJPJT',
  },
  {
    label: 'YMBKJPJT',
    value: 'YMBKJPJT',
  },
  {
    label: 'YCHBJPJT',
    value: 'YCHBJPJT',
  },
  {
    label: 'YOKOJPJM',
    value: 'YOKOJPJM',
  },
];
export const HKSwiftCodes =
  [
{label:'ABFLHKHH',value:'ABFLHKHH'},
{label:'ABNAHKAATRY',value:'ABNAHKAATRY'},
{label:'ABNAHKAA',value:'ABNAHKAA'},
{label:'ABNAHKAAIDJ',value:'ABNAHKAAIDJ'},
{label:'ABNAHKAAIPC',value:'ABNAHKAAIPC'},
{label:'ADHBHKH2',value:'ADHBHKH2'},
{label:'ABOCHKHH',value:'ABOCHKHH'},
{label:'ABOCHKHHCUS',value:'ABOCHKHHCUS'},
{label:'AIACHKHC',value:'AIACHKHC'},
{label:'AILIHKK2',value:'AILIHKK2'},
{label:'AIRRHKHH',value:'AIRRHKHH'},
{label:'THRMHKHH',value:'THRMHKHH'},
{label:'ABCHHKHH',value:'ABCHHKHH'},
{label:'ASEHHKHH',value:'ASEHHKHH'},
{label:'ASTNHKK2',value:'ASTNHKK2'},
{label:'ATIAHKH2',value:'ATIAHKH2'},
{label:'ANZBHKHXAAL',value:'ANZBHKHXAAL'},
{label:'ANZBHKHX',value:'ANZBHKHX'},
{label:'BOFAHKHU',value:'BOFAHKHU'},
{label:'BOFAHKHUTRS',value:'BOFAHKHUTRS'},
{label:'BOFAHKHUDBT',value:'BOFAHKHUDBT'},
{label:'BOFAHKHUFXD',value:'BOFAHKHUFXD'},
{label:'BBVAHKHH',value:'BBVAHKHH'},
{label:'BSCHHKHH',value:'BSCHHKHH'},
{label:'BKKBHKHH',value:'BKKBHKHH'},
{label:'BCTCHKHH',value:'BCTCHKHH'},
{label:'SARAHKHH',value:'SARAHKHH'},
{label:'BAERHKHH',value:'BAERHKHH'},
{label:'BNINHKHH',value:'BNINHKHH'},
{label:'BOFAHKHXSEC',value:'BOFAHKHXSEC'},
{label:'BOFAHKHX',value:'BOFAHKHX'},
{label:'BOFAHKHXSWP',value:'BOFAHKHXSWP'},
{label:'BOFAHKHXGMG',value:'BOFAHKHXGMG'},
{label:'BOFAHKHXAAM',value:'BOFAHKHXAAM'},
{label:'BOFAHKHXFIO',value:'BOFAHKHXFIO'},
{label:'BKCHHKHHCLS',value:'BKCHHKHHCLS'},
{label:'BKCHHKHHCSS',value:'BKCHHKHHCSS'},
{label:'BKCHHKHH838',value:'BKCHHKHH838'},
{label:'BKCHHKHH',value:'BKCHHKHH'},
{label:'CDFCHKHH',value:'CDFCHKHH'},
{label:'CDFCHKHHFPX',value:'CDFCHKHHFPX'},
{label:'BKCHHKHK',value:'BKCHHKHK'},
{label:'COMMHKHK',value:'COMMHKHK'},
{label:'COMMHKHH',value:'COMMHKHH'},
{label:'BKTLHKKH',value:'BKTLHKKH'},
{label:'DGCBHKHH',value:'DGCBHKHH'},
{label:'BEASHKHH',value:'BEASHKHH'},
{label:'BKIDHKHH',value:'BKIDHKHH'},
{label:'BOFMHKHH',value:'BOFMHKHH'},
{label:'BOFMHKHHFXM',value:'BOFMHKHHFXM'},
{label:'BOFMHKHHGTB',value:'BOFMHKHHGTB'},
{label:'BOFMHKHHPWM',value:'BOFMHKHHPWM'},
{label:'NOSCHKHH',value:'NOSCHKHH'},
{label:'NOSCHKHHMOC',value:'NOSCHKHHMOC'},
{label:'NOSCHKHHGFI',value:'NOSCHKHHGFI'},
{label:'BOSHHKHH',value:'BOSHHKHH'},
{label:'INGPHKHH',value:'INGPHKHH'},
{label:'INGPHKHHMTG',value:'INGPHKHHMTG'},
{label:'BKTWHKHH',value:'BKTWHKHH'},
{label:'SINOHKHH',value:'SINOHKHH'},
{label:'PICTHKAH',value:'PICTHKAH'},
{label:'PICTHKAHCOR',value:'PICTHKAHCOR'},
{label:'BARCHKHH',value:'BARCHKHH'},
{label:'BARCHKHW',value:'BARCHKHW'},
{label:'BZWLHKHH',value:'BZWLHKHH'},
{label:'CENAHKHR',value:'CENAHKHR'},
{label:'BNORHKHH',value:'BNORHKHH'},
{label:'BEEYHKH2',value:'BEEYHKH2'},
{label:'BIYPHKH2',value:'BIYPHKH2'},
{label:'BNDLHKK2',value:'BNDLHKK2'},
{label:'BNPAHKHHWMB',value:'BNPAHKHHWMB'},
{label:'BNPAHKHH',value:'BNPAHKHH'},
{label:'BNPAHKHHGCG',value:'BNPAHKHHGCG'},
{label:'BNPAHKHHCOM',value:'BNPAHKHHCOM'},
{label:'BNPAHKHP',value:'BNPAHKHP'},
{label:'PARBHKHHISI',value:'PARBHKHHISI'},
{label:'PARBHKHH',value:'PARBHKHH'},
{label:'BOENHKH2',value:'BOENHKH2'},
{label:'BOCFHKHK',value:'BOCFHKHK'},
{label:'BOCIHKHH',value:'BOCIHKHH'},
{label:'BPIIHKHH',value:'BPIIHKHH'},
{label:'BFOIHKHH',value:'BFOIHKHH'},
{label:'BBHCHKHH',value:'BBHCHKHH'},
{label:'CTBAHKHH',value:'CTBAHKHH'},
{label:'AGRIHKHX',value:'AGRIHKHX'},
{label:'CIBCHKHH',value:'CIBCHKHH'},
{label:'CFCMHKHH',value:'CFCMHKHH'},
{label:'CATHHKHH',value:'CATHHKHH'},
{label:'CMFGUS33',value:'CMFGUS33'},
{label:'UWCBHKHH',value:'UWCBHKHH'},
{label:'CBHAHKHH',value:'CBHAHKHH'},
{label:'CCNSHKHH',value:'CCNSHKHH'},
{label:'CNPIHKHK',value:'CNPIHKHK'},
{label:'CGHIHKKH',value:'CGHIHKKH'},
{label:'CCBCHKHH',value:'CCBCHKHH'},
{label:'CHBAHKHH',value:'CHBAHKHH'},
{label:'CSMHHKH2',value:'CSMHHKH2'},
{label:'CHBHHKHH',value:'CHBHHKHH'},
{label:'KWHKHKHH',value:'KWHKHKHH'},
{label:'KWHKHKHHCUS',value:'KWHKHKHHCUS'},
{label:'CCBQHKAXTRU',value:'CCBQHKAXTRU'},
{label:'CCBQHKAXCUS',value:'CCBQHKAXCUS'},
{label:'CCBQHKAXCML',value:'CCBQHKAXCML'},
{label:'CCBQHKAX',value:'CCBQHKAX'},
{label:'CCBQHKAXWHS',value:'CCBQHKAXWHS'},
{label:'CCBQHKAXTCD',value:'CCBQHKAXTCD'},
{label:'PCBCHKHH',value:'PCBCHKHH'},
{label:'PCBCHKHHIPA',value:'PCBCHKHHIPA'},
{label:'SDBCHKHH',value:'SDBCHKHH'},
{label:'EVERHKHH',value:'EVERHKHH'},
{label:'GDBKHKHH',value:'GDBKHKHH'},
{label:'CHVTHKHH',value:'CHVTHKHH'},
{label:'CMBCHKHH',value:'CMBCHKHH'},
{label:'MSBCHKHH',value:'MSBCHKHH'},
{label:'CHLNHKHH',value:'CHLNHKHH'},
{label:'CSNHHKH2',value:'CSNHHKH2'},
{label:'ZJCBHKHH',value:'ZJCBHKHH'},
{label:'CIYUHKHH',value:'CIYUHKHH'},
{label:'LCHBHKHH',value:'LCHBHKHH'},
{label:'CIBBHKHK',value:'CIBBHKHK'},
{label:'CILSHKH2',value:'CILSHKH2'},
{label:'CITIHKAX',value:'CITIHKAX'},
{label:'CITIHKAXIPB',value:'CITIHKAXIPB'},
{label:'CITIHKHXPBG',value:'CITIHKHXPBG'},
{label:'CITIHKHX',value:'CITIHKHX'},
{label:'CITIHKHXTLC',value:'CITIHKHXTLC'},
{label:'CITIHKHXCEA',value:'CITIHKHXCEA'},
{label:'CITIHKHXEFX',value:'CITIHKHXEFX'},
{label:'CITIHKHXBAR',value:'CITIHKHXBAR'},
{label:'CITIHKHXICE',value:'CITIHKHXICE'},
{label:'CITIHKHXLCB',value:'CITIHKHXLCB'},
{label:'CITIHKHXKIW',value:'CITIHKHXKIW'},
{label:'CITIHKHXREI',value:'CITIHKHXREI'},
{label:'CTFIHKHH',value:'CTFIHKHH'},
{label:'CITIHKHC',value:'CITIHKHC'},
{label:'CITIHKHCBAB',value:'CITIHKHCBAB'},
{label:'SBHKHKHH',value:'SBHKHKHH'},
{label:'CIHKHKHH',value:'CIHKHKHH'},
{label:'CLSAHKHH',value:'CLSAHKHH'},
{label:'CLSAHKHHCSB',value:'CLSAHKHHCSB'},
{label:'CLSAHKHHTBK',value:'CLSAHKHHTBK'},
{label:'CMBTHKH2',value:'CMBTHKH2'},
{label:'WUBAHKHH',value:'WUBAHKHH'},
{label:'CMBHHKH2',value:'CMBHHKH2'},
{label:'MMANHKH2',value:'MMANHKH2'},
{label:'COBAHKHX',value:'COBAHKHX'},
{label:'CTBAHKHK',value:'CTBAHKHK'},
{label:'CWFLHKHH',value:'CWFLHKHH'},
{label:'CPUHHKHH',value:'CPUHHKHH'},
{label:'CRLYHKHH',value:'CRLYHKHH'},
{label:'CRLYHKHHCOM',value:'CRLYHKHHCOM'},
{label:'AGRIHKHS',value:'AGRIHKHS'},
{label:'CMCIHKHH',value:'CMCIHKHH'},
{label:'CSFBHKHX',value:'CSFBHKHX'},
{label:'CSFBHKHXVIS',value:'CSFBHKHXVIS'},
{label:'CSHKHKHH',value:'CSHKHKHH'},
{label:'CRESHKHH',value:'CRESHKHH'},
{label:'CSFBHKHE',value:'CSFBHKHE'},
{label:'CSNMHKH2',value:'CSNMHKH2'},
{label:'CTCBHKHH',value:'CTCBHKHH'},
{label:'CTCBHKHH003',value:'CTCBHKHH003'},
{label:'CURFHKH2',value:'CURFHKH2'},
{label:'CURXHKH2',value:'CURXHKH2'},
{label:'DSBAHKHH',value:'DSBAHKHH'},
{label:'DWHKHKHH',value:'DWHKHKHH'},
{label:'DHBKHKHH',value:'DHBKHKHH'},
{label:'DHBKHKHHPCG',value:'DHBKHKHHPCG'},
{label:'DHBKHKHHMTG',value:'DHBKHKHHMTG'},
{label:'DBSSHKHH',value:'DBSSHKHH'},
{label:'DBSSHKHHIBD',value:'DBSSHKHHIBD'},
{label:'DEUTHKHHIPB',value:'DEUTHKHHIPB'},
{label:'DEUTHKHHGMO',value:'DEUTHKHHGMO'},
{label:'DEUTHKHH',value:'DEUTHKHH'},
{label:'GENOHKHH',value:'GENOHKHH'},
{label:'EPAHHKH2',value:'EPAHHKH2'},
{label:'FUMEHKHH',value:'FUMEHKHH'},
{label:'ESUNHKHH',value:'ESUNHKHH'},
{label:'EWBKHKHH',value:'EWBKHKHH'},
{label:'EPIIHKK2',value:'EPIIHKK2'},
{label:'EBLDHKHH',value:'EBLDHKHH'},
{label:'EFGBHKHH',value:'EFGBHKHH'},
{label:'GIBAHKHH',value:'GIBAHKHH'},
{label:'EXBKHKHH',value:'EXBKHKHH'},
{label:'FEINHKHH',value:'FEINHKHH'},
{label:'FILVHKH2',value:'FILVHKH2'},
{label:'NBADHKHH',value:'NBADHKHH'},
{label:'NBADHKHHGMO',value:'NBADHKHHGMO'},
{label:'FCBKHKHH',value:'FCBKHKHH'},
{label:'IBALHKHH',value:'IBALHKHH'},
{label:'FGAMHKH2',value:'FGAMHKH2'},
{label:'IFFUHKHH',value:'IFFUHKHH'},
{label:'FLICHKHH',value:'FLICHKHH'},
{label:'FLICHKH2',value:'FLICHKH2'},
{label:'GAAGHKH2',value:'GAAGHKH2'},
{label:'SHKOHKH2',value:'SHKOHKH2'},
{label:'GLCYHKH2',value:'GLCYHKH2'},
{label:'GCHLHKHH',value:'GCHLHKHH'},
{label:'GOAFHKHX',value:'GOAFHKHX'},
{label:'GSHBHKHK',value:'GSHBHKHK'},
{label:'GOCGHKH2',value:'GOCGHKH2'},
{label:'GRTMHKH2',value:'GRTMHKH2'},
{label:'GSHKHKHH',value:'GSHKHKHH'},
{label:'GJIHHKHH',value:'GJIHHKHH'},
{label:'HFLIHKHH',value:'HFLIHKHH'},
{label:'HFLIHKHHKCX',value:'HFLIHKHHKCX'},
{label:'HFLIHKHHKTX',value:'HFLIHKHHKTX'},
{label:'HFLIHKHHKNX',value:'HFLIHKHHKNX'},
{label:'HISAHKH2',value:'HISAHKH2'},
{label:'EAHAHKHH',value:'EAHAHKHH'},
{label:'HASEHKHH',value:'HASEHKHH'},
{label:'HASEHKHHSEC',value:'HASEHKHHSEC'},
{label:'HASEHKHHCLS',value:'HASEHKHHCLS'},
{label:'HASEHKHHSCF',value:'HASEHKHHSCF'},
{label:'HASEHKHHMTG',value:'HASEHKHHMTG'},
{label:'HASEHKH2',value:'HASEHKH2'},
{label:'GECGHKHH',value:'GECGHKHH'},
{label:'HDFCHKHH',value:'HDFCHKHH'},
{label:'HDITHKHH',value:'HDITHKHH'},
{label:'HESSHKK2',value:'HESSHKK2'},
{label:'SYNPHKHH',value:'SYNPHKHH'},
{label:'XHKFHKHH',value:'XHKFHKHH'},
{label:'XHKFHKHHTRE',value:'XHKFHKHHTRE'},
{label:'HKEXHKHH',value:'HKEXHKHH'},
{label:'HKEXHKHHTRE',value:'HKEXHKHHTRE'},
{label:'HKICHKHH',value:'HKICHKHH'},
{label:'HKMAHKHC',value:'HKMAHKHC'},
{label:'HKMCHKHH',value:'HKMCHKHH'},
{label:'HKMAHKHH',value:'HKMAHKHH'},
{label:'HKMAHKHHLTG',value:'HKMAHKHHLTG'},
{label:'HKMAHKHHCBA',value:'HKMAHKHHCBA'},
{label:'HKSCHKH2',value:'HKSCHKH2'},
{label:'HKSCHKHH',value:'HKSCHKHH'},
{label:'HKSCHKHHTRE',value:'HKSCHKHHTRE'},
{label:'HKSCHKH2IPO',value:'HKSCHKH2IPO'},
{label:'HLBBHKHH',value:'HLBBHKHH'},
{label:'HLBBHKHHIBW',value:'HLBBHKHHIBW'},
{label:'HSBCHKHH',value:'HSBCHKHH'},
{label:'HSBCHKHHHKH',value:'HSBCHKHHHKH'},
{label:'HSBCHKHHEBD',value:'HSBCHKHHEBD'},
{label:'HSBCHKHHIBM',value:'HSBCHKHHIBM'},
{label:'HSBCHKHHBLC',value:'HSBCHKHHBLC'},
{label:'HSBCHKHHMOA',value:'HSBCHKHHMOA'},
{label:'HSBCHKHHPRM',value:'HSBCHKHHPRM'},
{label:'HSBCHKHHMTG',value:'HSBCHKHHMTG'},
{label:'HSBCHKHHSBL',value:'HSBCHKHHSBL'},
{label:'HSBCHKHHBBO',value:'HSBCHKHHBBO'},
{label:'HSBCHKHHBHX',value:'HSBCHKHHBHX'},
{label:'HSBCHKHHCLS',value:'HSBCHKHHCLS'},
{label:'HSBCHKHHAVS',value:'HSBCHKHHAVS'},
{label:'HSBCHKHHGCA',value:'HSBCHKHHGCA'},
{label:'HSBCHKHHGCC',value:'HSBCHKHHGCC'},
{label:'HSBCHKHHGD2',value:'HSBCHKHHGD2'},
{label:'HSBCHKHHGDI',value:'HSBCHKHHGDI'},
{label:'HSBCHKHHNOS',value:'HSBCHKHHNOS'},
{label:'HSBCHKHHLAS',value:'HSBCHKHHLAS'},
{label:'HSBCHKHHPEC',value:'HSBCHKHHPEC'},
{label:'HSBCHKHHPBD',value:'HSBCHKHHPBD'},
{label:'HSBCHKHHPVP',value:'HSBCHKHHPVP'},
{label:'HSBCHKHHSEC',value:'HSBCHKHHSEC'},
{label:'HSBCHKHHTSD',value:'HSBCHKHHTSD'},
{label:'HSBCHKHHSCF',value:'HSBCHKHHSCF'},
{label:'HSBCHKHHUSI',value:'HSBCHKHHUSI'},
{label:'HSBCHKHHEXP',value:'HSBCHKHHEXP'},
{label:'HSBCHKHHIMP',value:'HSBCHKHHIMP'},
{label:'BLICHKHX',value:'BLICHKHX'},
{label:'HCBSHKHH',value:'HCBSHKHH'},
{label:'HSMBHKHH',value:'HSMBHKHH'},
{label:'HSBCHKHI',value:'HSBCHKHI'},
{label:'HSBCHKHISEL',value:'HSBCHKHISEL'},
{label:'HSBCHKHIFSA',value:'HSBCHKHIFSA'},
{label:'HSBCHKHIAVS',value:'HSBCHKHIAVS'},
{label:'HSBCHKHIGWS',value:'HSBCHKHIGWS'},
{label:'HSBCHKHIRFA',value:'HSBCHKHIRFA'},
{label:'HSMHHKHH',value:'HSMHHKHH'},
{label:'HSBCHKHP',value:'HSBCHKHP'},
{label:'JCALHKHH',value:'JCALHKHH'},
{label:'HSBCHKHT',value:'HSBCHKHT'},
{label:'HSBCHKHTGWS',value:'HSBCHKHTGWS'},
{label:'HNBKHKHH',value:'HNBKHKHH'},
{label:'HXBKHKHH',value:'HXBKHKHH'},
{label:'HCAIHKHH',value:'HCAIHKHH'},
{label:'HUSEHKHH',value:'HUSEHKHH'},
{label:'HGFNHKHK',value:'HGFNHKHK'},
{label:'ICBHHKHH',value:'ICBHHKHH'},
{label:'ICBHHKHHSFI',value:'ICBHHKHHSFI'},
{label:'ICICHKHHCOP',value:'ICICHKHHCOP'},
{label:'ICICHKHHCLR',value:'ICICHKHHCLR'},
{label:'ICICHKHHGTS',value:'ICICHKHHGTS'},
{label:'ICICHKHHRTG',value:'ICICHKHHRTG'},
{label:'ICICHKHH',value:'ICICHKHH'},
{label:'ICICHKHHIOG',value:'ICICHKHHIOG'},
{label:'ICICHKHHREM',value:'ICICHKHHREM'},
{label:'ICICHKHHTMG',value:'ICICHKHHTMG'},
{label:'IOBAHKHH',value:'IOBAHKHH'},
{label:'IOBAHKHHTST',value:'IOBAHKHHTST'},
{label:'UBHKHKHH',value:'UBHKHKHH'},
{label:'UBHKHKHHMTG',value:'UBHKHKHHMTG'},
{label:'ICBKHKHH',value:'ICBKHKHH'},
{label:'ICBKHKHHCCI',value:'ICBKHKHHCCI'},
{label:'FJIBHKHH',value:'FJIBHKHH'},
{label:'FJIBHKHHCUD',value:'FJIBHKHHCUD'},
{label:'FJIBHKHHPBD',value:'FJIBHKHHPBD'},
{label:'IBKOHKHH',value:'IBKOHKHH'},
{label:'INGBHKHH',value:'INGBHKHH'},
{label:'ISNTHKHH',value:'ISNTHKHH'},
{label:'IBKRHKHH',value:'IBKRHKHH'},
{label:'BCITHKHH',value:'BCITHKHH'},
{label:'IPALHKK2',value:'IPALHKK2'},
{label:'CHASHKAL',value:'CHASHKAL'},
{label:'CHASHKALFOP',value:'CHASHKALFOP'},
{label:'CHASHKALHOP',value:'CHASHKALHOP'},
{label:'CHASHKALNOM',value:'CHASHKALNOM'},
{label:'JAGOHKK2',value:'JAGOHKK2'},
{label:'JEFFHKHH',value:'JEFFHKHH'},
{label:'JGHRHKHK',value:'JGHRHKHK'},
{label:'JFIMHKHH',value:'JFIMHKHH'},
{label:'JFIMHKHHUTO',value:'JFIMHKHHUTO'},
{label:'JFIMHKHHTWM',value:'JFIMHKHHTWM'},
{label:'JFIMHKHHTCO',value:'JFIMHKHHTCO'},
{label:'JFIMHKHHNOM',value:'JFIMHKHHNOM'},
{label:'JFIMHKHHTAM',value:'JFIMHKHHTAM'},
{label:'JFIMHKHHCSD',value:'JFIMHKHHCSD'},
{label:'CHASHKHHLND',value:'CHASHKHHLND'},
{label:'CHASHKHHMTS',value:'CHASHKHHMTS'},
{label:'CHASHKHHTSD',value:'CHASHKHHTSD'},
{label:'CHASHKHHTRO',value:'CHASHKHHTRO'},
{label:'CHASHKHH',value:'CHASHKHH'},
{label:'CHASHKHP',value:'CHASHKHP'},
{label:'CHASHKHHFNO',value:'CHASHKHHFNO'},
{label:'CHASHKHHPBI',value:'CHASHKHHPBI'},
{label:'CHASHKHHFAX',value:'CHASHKHHFAX'},
{label:'CHASHKHHDCC',value:'CHASHKHHDCC'},
{label:'CHASHKHHBHK',value:'CHASHKHHBHK'},
{label:'CHASHKHHOIE',value:'CHASHKHHOIE'},
{label:'CHASHKHHDEV',value:'CHASHKHHDEV'},
{label:'CHASHKHHQAC',value:'CHASHKHHQAC'},
{label:'CHASHKHHUAT',value:'CHASHKHHUAT'},
{label:'KASIHKHH',value:'KASIHKHH'},
{label:'KREDHKHX',value:'KREDHKHX'},
{label:'KODBHKHH',value:'KODBHKHH'},
{label:'KOEXHKHH',value:'KOEXHKHH'},
{label:'KOEXHKHA',value:'KOEXHKHA'},
{label:'KEXAHKHH',value:'KEXAHKHH'},
{label:'KIHAHKK2',value:'KIHAHKK2'},
{label:'KHBAHKHH',value:'KHBAHKHH'},
{label:'KIEAHKH2',value:'KIEAHKH2'},
{label:'KVBTHKH2',value:'KVBTHKH2'},
{label:'LBOTHKHH',value:'LBOTHKHH'},
{label:'BLFLHKHH',value:'BLFLHKHH'},
{label:'BLFLHKHHEXC',value:'BLFLHKHHEXC'},
{label:'FTRDHKHH',value:'FTRDHKHH'},
{label:'LOIMHKHH',value:'LOIMHKHH'},
{label:'LIICHKHH',value:'LIICHKHH'},
{label:'LIVIHKHH',value:'LIVIHKHH'},
{label:'LOYDHKHH',value:'LOYDHKHH'},
{label:'LBMGHKHH',value:'LBMGHKHH'},
{label:'MACQHKHH',value:'MACQHKHH'},
{label:'MACQHKHHCSH',value:'MACQHKHHCSH'},
{label:'BSHLHKHHTHA',value:'BSHLHKHHTHA'},
{label:'BSHLHKHHHKM',value:'BSHLHKHHHKM'},
{label:'BSHLHKHHSGM',value:'BSHLHKHHSGM'},
{label:'BSHLHKHHSBL',value:'BSHLHKHHSBL'},
{label:'BSHLHKHH',value:'BSHLHKHH'},
{label:'BSHLHKHHKRW',value:'BSHLHKHHKRW'},
{label:'BSHLHKHHKEF',value:'BSHLHKHHKEF'},
{label:'MPACHKHR',value:'MPACHKHR'},
{label:'MFCTHKHH',value:'MFCTHKHH'},
{label:'MSHQHKHH',value:'MSHQHKHH'},
{label:'MSHQHKHHHKD',value:'MSHQHKHHHKD'},
{label:'MSHQHKHHHKH',value:'MSHQHKHHHKH'},
{label:'MSHNHKH2',value:'MSHNHKH2'},
{label:'MBBEHKHH',value:'MBBEHKHH'},
{label:'ICBCHKHH',value:'ICBCHKHH'},
{label:'MPELHKHH',value:'MPELHKHH'},
{label:'MLFEHKHH',value:'MLFEHKHH'},
{label:'MLFEHKHHAUV',value:'MLFEHKHHAUV'},
{label:'MLFEHKHHGLO',value:'MLFEHKHHGLO'},
{label:'MGBHHKHH',value:'MGBHHKHH'},
{label:'MTBCHKHH',value:'MTBCHKHH'},
{label:'MHCBHKHH',value:'MHCBHKHH'},
{label:'MHSCHKHH',value:'MHSCHKHH'},
{label:'MOIHHKHH',value:'MOIHHKHH'},
{label:'MOHKHKH2',value:'MOHKHKH2'},
{label:'MSHKHKHXFXO',value:'MSHKHKHXFXO'},
{label:'MSHKHKHXSGX',value:'MSHKHKHXSGX'},
{label:'MSHKHKHXCLS',value:'MSHKHKHXCLS'},
{label:'MSHKHKHXGPR',value:'MSHKHKHXGPR'},
{label:'MSHKHKHX',value:'MSHKHKHX'},
{label:'MSHKHKHXIED',value:'MSHKHKHXIED'},
{label:'MSHKHKHXPTE',value:'MSHKHKHXPTE'},
{label:'MSAIHKHH',value:'MSAIHKHH'},
{label:'MOXBHKHK',value:'MOXBHKHK'},
{label:'BOTKHKHH',value:'BOTKHKHH'},
{label:'MFHKHKHH',value:'MFHKHKHH'},
{label:'NYCBHKHH',value:'NYCBHKHH'},
{label:'NATAHKHH',value:'NATAHKHH'},
{label:'NBPAHKHH',value:'NBPAHKHH'},
{label:'NBPAHKHHKLN',value:'NBPAHKHHKLN'},
{label:'NATXHKHX',value:'NATXHKHX'},
{label:'RBOSHKHX',value:'RBOSHKHX'},
{label:'NTATHKH2',value:'NTATHKH2'},
{label:'NHSEHKH2',value:'NHSEHKH2'},
{label:'NOBGHKHH',value:'NOBGHKHH'},
{label:'NOMAHKHH',value:'NOMAHKHH'},
{label:'NOMHHKHH',value:'NOMHHKHH'},
{label:'NACFHKHH',value:'NACFHKHH'},
{label:'IBOTHKHH',value:'IBOTHKHH'},
{label:'WIHBHKHH',value:'WIHBHKHH'},
{label:'OAMHHKH2',value:'OAMHHKH2'},
{label:'OSIFHKH2',value:'OSIFHKH2'},
{label:'OCCPHKHH',value:'OCCPHKHH'},
{label:'OCCPHKHHTRE',value:'OCCPHKHHTRE'},
{label:'OTCNHKA2',value:'OTCNHKA2'},
{label:'OTPAHKH2',value:'OTPAHKH2'},
{label:'OCBCHKHH',value:'OCBCHKHH'},
{label:'PAVAHKK2',value:'PAVAHKK2'},
{label:'PEAGHKHK',value:'PEAGHKHK'},
{label:'PAHNHKK2',value:'PAHNHKK2'},
{label:'PRBLHKHH',value:'PRBLHKHH'},
{label:'PNBMHKHH',value:'PNBMHKHH'},
{label:'SZDBHKHH',value:'SZDBHKHH'},
{label:'PCAGHKHA',value:'PCAGHKHA'},
{label:'PCAGHKHH',value:'PCAGHKHH'},
{label:'PONCHKHH',value:'PONCHKHH'},
{label:'BMRIHKHH',value:'BMRIHKHH'},
{label:'CBHKHKHH',value:'CBHKHKHH'},
{label:'PUNBHKHH',value:'PUNBHKHH'},
{label:'QNBAHKHH',value:'QNBAHKHH'},
{label:'QRMOHKH2',value:'QRMOHKH2'},
{label:'RDHKHKH2',value:'RDHKHKH2'},
{label:'RABOHKHH',value:'RABOHKHH'},
{label:'BILLHKHT',value:'BILLHKHT'},
{label:'EATRHKHK',value:'EATRHKHK'},
{label:'EATRHKHKSCH',value:'EATRHKHKSCH'},
{label:'EATRHKHKSHK',value:'EATRHKHKSHK'},
{label:'RIHCHKHH',value:'RIHCHKHH'},
{label:'ROYCHKHHISA',value:'ROYCHKHHISA'},
{label:'ROYCHKHH',value:'ROYCHKHH'},
{label:'ROYCHKHHPBB',value:'ROYCHKHHPBB'},
{label:'SWHQHKHHEDU',value:'SWHQHKHHEDU'},
{label:'SWHQHKHH',value:'SWHQHKHH'},
{label:'PBOCHKHH',value:'PBOCHKHH'},
{label:'SSHKHKHK',value:'SSHKHKHK'},
{label:'SDGSHKH2',value:'SDGSHKH2'},
{label:'SEOCHKHH',value:'SEOCHKHH'},
{label:'SEOCHKHHTRE',value:'SEOCHKHHTRE'},
{label:'SGSEHKHHGSC',value:'SGSEHKHHGSC'},
{label:'SGSEHKHHHKA',value:'SGSEHKHHHKA'},
{label:'SGSEHKHHHHR',value:'SGSEHKHHHHR'},
{label:'SGSEHKHHHKO',value:'SGSEHKHHHKO'},
{label:'SGSEHKHH',value:'SGSEHKHH'},
{label:'SCBKHKHH',value:'SCBKHKHH'},
{label:'SPDBHKHH',value:'SPDBHKHH'},
{label:'SPDBHKHHCCM',value:'SPDBHKHHCCM'},
{label:'SHBKHKHX',value:'SHBKHKHX'},
{label:'SHBKHKHXIBC',value:'SHBKHKHXIBC'},
{label:'SCNRHKHH',value:'SCNRHKHH'},
{label:'SICOHKHH',value:'SICOHKHH'},
{label:'SILDHKH2',value:'SILDHKH2'},
{label:'SEKLHKHC',value:'SEKLHKHC'},
{label:'ESSEHKHH',value:'ESSEHKHH'},
{label:'SKHCHKK2',value:'SKHCHKK2'},
{label:'NKSCHKHH',value:'NKSCHKHH'},
{label:'SOGEHKHH',value:'SOGEHKHH'},
{label:'SOTNHKH2',value:'SOTNHKH2'},
{label:'SOTNHKH2HWA',value:'SOTNHKH2HWA'},
{label:'SOTNHKH2ALL',value:'SOTNHKH2ALL'},
{label:'SOTNHKH2TIC',value:'SOTNHKH2TIC'},
{label:'SDISHKH2',value:'SDISHKH2'},
{label:'SDISHKH2EQU',value:'SDISHKH2EQU'},
{label:'SDISHKH2FIC',value:'SDISHKH2FIC'},
{label:'SIFHHKHH',value:'SIFHHKHH'},
{label:'SCBLHKHHMAC',value:'SCBLHKHHMAC'},
{label:'SCBLHKHH',value:'SCBLHKHH'},
{label:'SCBLHKHHZOP',value:'SCBLHKHHZOP'},
{label:'SCBLHKHHZHS',value:'SCBLHKHHZHS'},
{label:'SCBLHKHHZPB',value:'SCBLHKHHZPB'},
{label:'SCBLHKHHZSS',value:'SCBLHKHHZSS'},
{label:'SCBLHKHHWHK',value:'SCBLHKHHWHK'},
{label:'SCBLHKHHSGE',value:'SCBLHKHHSGE'},
{label:'SCBLHKHHMTG',value:'SCBLHKHHMTG'},
{label:'SBINHKHH',value:'SBINHKHH'},
{label:'SBOSHKHX',value:'SBOSHKHX'},
{label:'SBOSHKHXAGC',value:'SBOSHKHXAGC'},
{label:'SBOSHKHXTAD',value:'SBOSHKHXTAD'},
{label:'STYSHKHH',value:'STYSHKHH'},
{label:'STYSHKH2',value:'STYSHKH2'},
{label:'STPVHKHH',value:'STPVHKHH'},
{label:'SMBCHKHH',value:'SMBCHKHH'},
{label:'STBCHKHH',value:'STBCHKHH'},
{label:'SWHQHKHKSVC',value:'SWHQHKHKSVC'},
{label:'SWHQHKHK',value:'SWHQHKHK'},
{label:'SYANHKH2',value:'SYANHKH2'},
{label:'TSBLHKHH',value:'TSBLHKHH'},
{label:'TYBLHKKW',value:'TYBLHKKW'},
{label:'TPBKHKHH',value:'TPBKHKHH'},
{label:'TAMYHKH2',value:'TAMYHKH2'},
{label:'TSIBHKHH',value:'TSIBHKHH'},
{label:'MBBTHKHH',value:'MBBTHKHH'},
{label:'TACBHKHH',value:'TACBHKHH'},
{label:'MKTBHKHH',value:'MKTBHKHH'},
{label:'IRVTHKHX',value:'IRVTHKHX'},
{label:'CHGKHKHH',value:'CHGKHKHH'},
{label:'HABKHKHH',value:'HABKHKHH'},
{label:'BBDAHKHX',value:'BBDAHKHX'},
{label:'BBDAHKHXAVS',value:'BBDAHKHXAVS'},
{label:'BBDAHKHXTAR',value:'BBDAHKHXTAR'},
{label:'BTFEHKHHBKK',value:'BTFEHKHHBKK'},
{label:'BTFEHKHHBOM',value:'BTFEHKHHBOM'},
{label:'BTFEHKHHDOH',value:'BTFEHKHHDOH'},
{label:'BTFEHKHHDUB',value:'BTFEHKHHDUB'},
{label:'BTFEHKHHFSA',value:'BTFEHKHHFSA'},
{label:'BTFEHKHHAVS',value:'BTFEHKHHAVS'},
{label:'BTFEHKHHKHI',value:'BTFEHKHHKHI'},
{label:'BTFEHKHHIMO',value:'BTFEHKHHIMO'},
{label:'BTFEHKHHMNL',value:'BTFEHKHHMNL'},
{label:'BTFEHKHHRFA',value:'BTFEHKHHRFA'},
{label:'BTFEHKHHVNI',value:'BTFEHKHHVNI'},
{label:'BTFEHKHH',value:'BTFEHKHH'},
{label:'BTFEHKHHISD',value:'BTFEHKHHISD'},
{label:'BTFEHKHHRTS',value:'BTFEHKHHRTS'},
{label:'KDHKHKHH',value:'KDHKHKHH'},
{label:'SCSBHKHH',value:'SCSBHKHH'},
{label:'SIGAHKHH',value:'SIGAHKHH'},
{label:'SHIZHKHH',value:'SHIZHKHH'},
{label:'XHKGHKHH',value:'XHKGHKHH'},
{label:'XHKGHKHHTRE',value:'XHKGHKHHTRE'},
{label:'TDOMHKHH',value:'TDOMHKHH'},
{label:'TRRFHKH2',value:'TRRFHKH2'},
{label:'UBSWHKHHE1M',value:'UBSWHKHHE1M'},
{label:'UBSWHKHH',value:'UBSWHKHH'},
{label:'UBSWHKHHCLS',value:'UBSWHKHHCLS'},
{label:'UBSWHKHHCIC',value:'UBSWHKHHCIC'},
{label:'UBSWHKH2',value:'UBSWHKH2'},
{label:'SWDRHKH2',value:'SWDRHKH2'},
{label:'UBSEHKH2',value:'UBSEHKH2'},
{label:'SBFAHKH2',value:'SBFAHKH2'},
{label:'UCBAHKHH',value:'UCBAHKHH'},
{label:'BVBEHKHH',value:'BVBEHKHH'},
{label:'UBPGHKHX',value:'UBPGHKHX'},
{label:'UBINHKHH',value:'UBINHKHH'},
{label:'UBINHKHHLCR',value:'UBINHKHHLCR'},
{label:'UETCHKH2',value:'UETCHKH2'},
{label:'UOVBHKHH',value:'UOVBHKHH'},
{label:'UOVBHKHHCMS',value:'UOVBHKHHCMS'},
{label:'UECEHKHK',value:'UECEHKHK'},
{label:'VACKHKH2',value:'VACKHKH2'},
{label:'BFTVHKHH',value:'BFTVHKHH'},
{label:'VTBCHKHK',value:'VTBCHKHK'},
{label:'WEDIHKHH',value:'WEDIHKHH'},
{label:'PNBPHKHH',value:'PNBPHKHH'},
{label:'PNBPHKHHBDP',value:'PNBPHKHHBDP'},
{label:'WPACHKHX',value:'WPACHKHX'},
{label:'WPACHKHXTRD',value:'WPACHKHXTRD'},
{label:'WPACHKHXTSY',value:'WPACHKHXTSY'},
{label:'WSMHHKHH',value:'WSMHHKHH'},
{label:'EXMTHKHH',value:'EXMTHKHH'},
{label:'WIHKHKH2',value:'WIHKHKH2'},
{label:'HVBKHKHH',value:'HVBKHKHH'},
{label:'WTAMHKH2',value:'WTAMHKH2'},
{label:'XTRAHKH2',value:'XTRAHKH2'},
{label:'OURBHKHH',value:'OURBHKHH'},
{label:'YXSCHKH2',value:'YXSCHKH2'},
{label:'AABLHKHH',value:'AABLHKHH'},
{label:'ZEALHKH2',value:'ZEALHKH2'},
{label:'ZAMNHKH2',value:'ZAMNHKH2'},
{label:'ZURIHKHH',value:'ZURIHKHH'}
];
export const SWIFT_CODES = (key:any)=>{
  let res = SwiftCodes;
switch(key){
  case "HKD":
  res= HKSwiftCodes;
  break;
  default: res=SwiftCodes;

}
return res;
} ;



